### ISSUE TITLE
DRb::DRbConnError: too large packet

### ISSUE THREAD

**Issue by unsown** [hicknhack-software/rails-disco#14]
I got DRbConnError while trying to post a new event. The error turned out to be caused by the different port I set in the disco.yml. It seems that the set_config function below is not used to set the configuration.
https://github.com/hicknhack-software/rails-disco/blob/master/active_event/lib/active_event/domain.rb#L50

**Comment by arBmind** [comment]
@unsown Thank you very much for the first bug report on Rails Disco.

I have implemented a quick fix. Now disco.yml is read by the Domain module as well.

Feel free to reopen the issue, if it does not help.
