### ISSUE TITLE
Disco new (with existing project)

### ISSUE THREAD

**Issue by enricribas** [hicknhack-software/rails-disco#20]
In Rails 4.2.1 project
in the actual root of the project

```
disco new
```

results in ...

```
No value provided for required arguments 'app_path'
```

as per docs

> (Note: You can also add Rails Disco to an existing Rails application. Simply omit the application name and run the command inside your application.)

Maybe I missed something? Thanks.

**Comment by arBmind** [comment]
This seems to be a bug. Thank you for reporting it.
I guess this feature was simply forgotten.
I will take a look into it as soon as I find time - what might take a while.
