### ISSUE TITLE
Drb Issues

### ISSUE THREAD

**Issue by enricribas** [hicknhack-software/rails-disco#21]
This one is probably my fault but not sure what else I need to set up. 
RabbitMQ is working fine. 
Using Puma
created project with Disco New

```
DRb::DRbConnError in TeamsController#create
druby://127.0.0.1:8787 - #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 8787>
```

following the SitePoint tutorial and trying to create a team.
Rails 4.1.12
Rails Disco 0.5.3

**Comment by arBmind** [comment]
drb is used to connect to the domain server.
Are you running the domain? - It may have stopped because of an error.

**Comment by enricribas** [comment]
Completely my fault. I ran `rails server` instead of `disco server` which of course only runs the main "projection" server.

Feel free to close.
